version: "3.9"
services:
  postgres:
    image: postgres:14.5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  
  postgres-keycloak:
    image: postgres:14.5
    container_name: restaurant-postgres-keycloak
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloakdata:/var/lib/postgresql/data
  
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: ${IDENTITY_ADMIN_USER:-admin}
      KEYCLOAK_PASSWORD: ${IDENTITY_ADMIN_PW:-admin}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/restaurant-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./docker/kc:/opt/jboss/keycloak/imports
    depends_on:
      - postgres-keycloak  

  sonarqube:
    profiles:
      - sonar
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  
  zipkin:
    profiles:
      - zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  keycloakdata:
