spring:
  datasource:
    url: jdbc:postgresql://postgres/restaurant_db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/blueprint/protocol/openid-connect/certs