spring:
  application:
    name: configserver
  profiles:
    active: native # git -- if we hold the information in a git repo
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8071